"""Render a resolved role selection into one idempotent bash script.

The same script configures an instance at both points in its life:

- at deploy, cloud-init writes it to ``SCRIPT_PATH`` and runs it from
  ``runcmd`` (the seed also drops the one-time Tailscale auth key at
  ``AUTHKEY_PATH``);
- on reconfigure, the controller writes it through the QEMU guest agent and
  runs it the same way.

No SSH is involved either way, and every step is safe to repeat. Output goes
to ``LOG_PATH`` so a failure can be read back through the guest agent.
"""

from __future__ import annotations

import base64
import posixpath
import shlex
from collections.abc import Callable

SCRIPT_PATH = "/var/lib/homecloud/provision.sh"
AUTHKEY_PATH = "/var/lib/homecloud/tailscale-authkey"
LOG_PATH = "/var/log/homecloud-provision.log"

_HEADER = """\
#!/bin/bash
# Generated by the homecloud controller; rewritten on every reconfigure.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
"""


def _q(value: str) -> str:
    return shlex.quote(value)


def _bool(value: object) -> str:
    return "true" if value else "false"


def _packages(vars: dict, _user: str, _hostname: str) -> list[str]:
    packages = vars.get("packages") or []
    if not packages:
        return []
    return [
        "apt-get update -q",
        "apt-get install -y -q " + " ".join(_q(p) for p in packages),
    ]


def _tailscale(vars: dict, user: str, hostname: str) -> list[str]:
    flags = (
        f"--accept-routes={_bool(vars.get('tailscale_accept_routes'))} "
        f"--ssh={_bool(vars.get('tailscale_ssh'))}"
    )
    return [
        "command -v tailscale >/dev/null || curl -fsSL https://tailscale.com/install.sh | sh",
        "systemctl enable --now tailscaled",
        # The auth key is only present on first boot; it is single-use, and is
        # deleted as soon as it has been spent.
        f"if [ -s {AUTHKEY_PATH} ]; then",
        f"  tailscale up --auth-key=file:{AUTHKEY_PATH} --hostname={_q(hostname)} {flags}",
        f"  rm -f {AUTHKEY_PATH}",
        "fi",
        f"tailscale set --operator={_q(user)} --auto-update=true {flags}",
    ]


def _docker(_vars: dict, user: str, _hostname: str) -> list[str]:
    return [
        "command -v docker >/dev/null || curl -fsSL https://get.docker.com | sh",
        "systemctl enable --now docker",
        f"usermod -aG docker {_q(user)}",
    ]


def _uv(_vars: dict, _user: str, _hostname: str) -> list[str]:
    return [
        "[ -x /usr/local/bin/uv ] || "
        "curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin sh",
    ]


def _files(vars: dict, _user: str, _hostname: str) -> list[str]:
    lines: list[str] = []
    for entry in vars.get("files") or []:
        path = entry["path"]
        # base64 keeps arbitrary content (quotes, heredoc markers) intact.
        data = base64.b64encode(entry.get("content", "").encode()).decode()
        lines.append(f"mkdir -p {_q(posixpath.dirname(path) or '/')}")
        lines.append(f"printf %s {_q(data)} | base64 -d > {_q(path)}")
        if entry.get("mode"):
            lines.append(f"chmod {_q(entry['mode'])} {_q(path)}")
        if entry.get("owner"):
            lines.append(f"chown {_q(entry['owner'])} {_q(path)}")
    return lines


def _commands(vars: dict, _user: str, _hostname: str) -> list[str]:
    return [f"bash -c {_q(command)}" for command in vars.get("commands") or []]


RENDERERS: dict[str, Callable[[dict, str, str], list[str]]] = {
    "packages": _packages,
    "tailscale": _tailscale,
    "docker": _docker,
    "uv": _uv,
    "files": _files,
    "commands": _commands,
}


def render_script(roles: list[dict], *, user: str, hostname: str) -> str:
    """Bash for *roles* (already resolved by ``catalog.resolve_roles``, so in order)."""
    parts = [_HEADER]
    for role in roles:
        render = RENDERERS.get(role["id"])
        if render is None:
            raise ValueError(f"No script renderer for role {role['id']!r}")
        body = render(role.get("vars") or {}, user, hostname)
        if not body:
            continue
        parts.append(f"\necho {_q('▸ ' + role['id'])}\n" + "\n".join(body) + "\n")
    parts.append("\necho '▸ done'\n")
    return "".join(parts)


def run_command() -> list[str]:
    """argv that runs the script and keeps its output in ``LOG_PATH``."""
    return ["bash", "-c", f"bash {SCRIPT_PATH} > {LOG_PATH} 2>&1"]
